# Generated by Django 4.2.7 on 2023-12-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_note_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
