# Generated by Django 4.2.7 on 2023-12-14 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_alter_category_title_alter_note_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="reminder",
        ),
    ]
