# Generated by Django 4.2.7 on 2023-12-14 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0006_remove_note_reminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="reminder",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
