# Generated by Django 4.2.7 on 2023-12-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0007_note_reminder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AddField(
            model_name="category",
            name="category_id",
            field=models.IntegerField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
